apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: service-blue-virtual-router
  namespace: my-apps
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: service-blue-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: service-blue
              weight: 1