apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  finalizers:
  - ingress.k8s.aws/resources
  labels:
    app: ingress
  name: ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
