apiVersion: v1
kind: Service
metadata:
  name: service-blue
  namespace: default
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    app: service-blue
spec:
  selector:
    app: service-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-red
  namespace: default
  labels:
    app: service-red
spec:
  selector:
    app: service-red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-violet
  namespace: default
  labels:
    app: service-violet
spec:
  selector:
    app: service-violet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-purple
  namespace: default
  labels:
    app: service-purple
spec:
  selector:
    app: service-purple
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000